version: "3.3"
   
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: testpass
      MYSQL_DATABASE: twitter
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin

  memcached:
    image: docker.io/bitnami/memcached:1
    ports:
      - '11211:11211'

  redis:
    image: "redis:alpine"
    ports:
      - '6379:6379'

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - memcached
      - redis

volumes:
  db_data: {}
