# Generated by Django 3.1.3 on 2021-05-11 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeeds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsfeed',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
