# Generated by Django 3.1.3 on 2021-06-27 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeeds', '0002_auto_20210511_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsfeed',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
